name: my_galf
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  hovering: ^1.0.4
  flutter_dash: ^1.0.0
  flutter_sticky_widgets: ^0.0.3
  http: ^0.13.5
  dio: ^5.1.0
  flutter_spinkit: ^5.1.0
  image_network: ^2.5.1
  intl: ^0.18.0
  dotted_border: ^2.0.0+3
  shared_preferences: ^2.1.0
  path_provider: ^2.0.14
  sqflite: ^2.2.6
  badges: ^3.0.3
  provider: ^6.0.5
  localstorage: ^4.0.1+2
  get_storage: ^2.1.1
  sticky_headers: ^0.3.0+2
  zoom_widget: ^2.0.0
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.0.2
  getwidget: ^2.0.4
  dependencies:
  dropdown_button2: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: test
      fonts:
        - asset: assets/fonts/test.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    - family: jadoo
      fonts:
        - asset: assets/fonts/KonkhmerSleokchher-Regular.ttf
